### ISSUE TITLE
Will there be native operations over entities? 

### ISSUE THREAD

**Issue by antontidev** [Leopotam/ecslite-threads-unity#1]
New ecs lite is good, but how I should perform common operations over entities from Job/Burst like: 1) remove/add components 2) check is there a component of certain type on entity, 3) entity deletion. For now we only have showcase of Get component operation. For all listed operations in Svelto.ECS there implemented Native operations. Any chances that you will add such behaviour to your new framework?

**Comment by Leopotam** [comment]
@antontidev
> remove/add components

You cant change world state somehow from jobs, just change component states.

> check is there a component of certain type on entity
What does it mean? You want to touch random component on entity that was not added to constraints list of filter? You cant. Technically, you can (in .net threads) send pools instances to threads and call `pool.Has()` method, but not from jobs/burst.

> Any chances that you will add such behaviour to your new framework?

No, `ecslite` was created as engine agnostic framework with small pure c# core and extensions around it. `ecslite-threads-unity` - just one of these extensions. It means - you can try to create custom extension for work with native collections like command buffers, etc, but I have no plans to do it.

**Comment by antontidev** [comment]
You can wrap pool info like sparse and dense with additional NativeCollections (NativeList, NativeHashMap), which will handle component adding/deleting from entity, entity destroying, and then after job completion just go through this collections and apply changes to outer managed EcsPool<>. For my opinion, this will be more practically significant.

**Comment by Leopotam** [comment]
@antontidev
> You can wrap pool info like sparse and dense with additional NativeCollections

I cant due to:
> No, ecslite was created as engine agnostic framework with small pure c# core and extensions around it.

And from [ecslite README](https://github.com/Leopotam/ecslite):
> Performance, zero/small memory allocations/footprint, [b]no dependencies on any game engine[/b] - main goals of this project.

This optional repo just simple wrapper for working with jobs/burst, nothing more. I have no any plans to make vendor-lock solution, if you need full native collection support - better to wait for unity DOTS.
