### ISSUE TITLE
Up to 4 components pools looks not so scaly

### ISSUE THREAD

**Issue by antontidev** [Leopotam/ecslite-threads-unity#3]
Why not just allow programmer to fill out content of the Init method? You can simply move initialization right to abstract Init method of BaseJobSystem, get rid of multiple base job systems class overloads, add method to wrap component pool with sparse array in BaseJobSystem class, and after job completion call Unwrapp on all registered pools.

**Comment by Leopotam** [comment]
@antontidev you can fork this or create your own extensions based on this one.
